### ISSUE TITLE
Cannot import name 'slice_column' from 'pinnicle.utils.backends_specified'!

### ISSUE THREAD

**Issue by MostafaCham** [enigne/PINN_ICE#50]
When I tried to run the Upernavik.ipynb notebook in the examples directory, I got the error below. I checked the backends_specified.py file it seems there is no function named "slice_column" and "jacobian" and you are assigning them in the if condition at the end of the file. I think the reason is that they are not defined at the module level, and this is causing the issue. 
Maybe adding "__all__ = ['slice_column', 'jacobian']" at the end of the file fixes the issue.

ImportError                               Traceback (most recent call last)
[<ipython-input-5-0d79f15b3ac4>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import pinnicle as pinn
      2 import os
      3 import numpy as np
      4 from datetime import datetime
      5 import deepxde as dde

2 frames
[/content/PINNICLE/pinnicle/__init__.py](https://localhost:8080/#) in <module>
----> 1 from .parameter import *
      2 from . import utils
      3 from . import physics
      4 from . import modeldata
      5 from . import nn

[/content/PINNICLE/pinnicle/parameter.py](https://localhost:8080/#) in <module>
      1 from abc import ABC, abstractmethod
----> 2 from .utils import data_misfit
      3 
      4 
      5 class ParameterBase(ABC):

[/content/PINNICLE/pinnicle/utils/__init__.py](https://localhost:8080/#) in <module>
      1 from .helper import *
----> 2 from .backends_specified import slice_column, jacobian, slice_function_jax
      3 from .history import History
      4 from .data_misfit import get
      5 from .plotting import plot_solutions, plot_dict_data, plot_data, plot_nn, tripcolor_similarity, tripcolor_residuals, diffplot, resplot, plot_tracks

ImportError: cannot import name 'slice_column' from 'pinnicle.utils.backends_specified' (/content/PINNICLE/pinnicle/utils/backends_specified.py)

**Comment by enigne** [comment]
Could you check what backend you are using `from deepxde.backend import backend_name`?

**Comment by MostafaCham** [comment]
It is the default backend: Setting the default backend to "tensorflow.compat.v1".

**Comment by enigne** [comment]
ok, I see. Currently, PINNICLE only support `tensorflow` (which is version 2), `pytorch` and `jax`. Unfortunately, tensorflow v1 is not supported. If you want, you can change your backend setting in `~/.deepxde/config.json` to `tensorflow`
